repos:
  # Standard hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=3500']
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: check-byte-order-marker  # Forbid UTF-8 byte-order markers
      - id: trailing-whitespace

  # Python hooks
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.17.0
    hooks:
      - id: pyupgrade
        args: [--py36-plus]

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        args: ["--line-length=100"]


  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args: ["--ignore=E501"]


  # Cmake hooks
  - repo: local
    hooks:
      - id: ament_lint_cmake
        name: ament_lint_cmake
        description: Check format of CMakeLists.txt files.
        stages: [pre-commit]
        entry: ament_lint_cmake
        language: system
        files: CMakeLists.txt$

  # ament_copyright is somehow broken for the BSD-3-Clause license: https://github.com/ament/ament_lint/issues/483
  # We therefore disable it for now
  # Copyright
  #- repo: local
  #  hooks:
  #    - id: ament_copyright
  #      name: ament_copyright
  #      description: Check if copyright notice is available in all files.
  #      stages: [pre-commit]
  #      entry: ament_copyright
  #      language: system

  # Spellcheck in comments and docs
  # skipping of *.svg files is not working...
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        args: ['--write-changes']
        exclude: \.(svg|pyc)$
